AWSTemplateFormatVersion: '2010-09-09'
Description: Jupyter Executor Service.
Resources:
  JupyterExecutor:
    Properties:
      CodeUri: s3://aws-nbformat-demo/969d72559445d7d59696a46dfb347cf5
      Events:
        ExecuteNotebook:
          Properties:
            Method: any
            Path: /
          Type: Api
      Handler: main.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
