AWSTemplateFormatVersion: '2010-09-09'
Description: Jupyter Executor Service.
Resources:
  JupyterExecutor:
    Properties:
      CodeUri: s3://alsetlambda/63820c8cf15e611749fd3e4cb05bcd11
      Events:
        ExecuteNotebook:
          Properties:
            Method: any
            Path: /
          Type: Api
      Handler: main.handler
      MemorySize: 512
      Runtime: python3.6
      Timeout: 180
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
