AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Jupyter Executor Service.
Resources:
  JupyterExecutor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.6
      CodeUri: .
      Events:
        ExecuteNotebook:
          Type: Api
          Properties:
            Path: /
            Method: any